[project]
name = "hwidgets"
description = "Customized PySide6 widgets for Herlegon tools"
readme = "README.md"
authors = [
    { name = "Jep Etau" }
]
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "hytils",
    "numpy",
    "PySide6_Essentials",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/herlegon/hwidgets"

[build-system]
requires = ["setuptools >= 80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["hwidgets"]
exclude = ["tests*", "scripts", "rlg_widgets"]

[tool.setuptools.dynamic]
version = { attr = "hwidgets.__version__" }

[tool.black]
line-length = 90
target-version = ['py312']

[tool.ruff]
exclude = ["*"]
