[window]
window = "#1c1d20"

[default]
bgd = "#2a2a2a"
hover = "#3a3a3a"
selection = "#5e7ce0"
pressed = "#5e5e5e"
disabled_bgd = "#2a2a2a"
border = "#4a4a4a"
border_radius = 8
height = 40

font_family = "Inter"
font_size = 10
font_weight = 400
font_color = "#d4d4d4"
font_color_disabled = "#666667"
font_color_selected = "#ffffff"
font_color_checked = "#ffffff"

[frame]
bgd ="#212224"

[card]
border = "#3a3a3a"

[divider]
normal = "#3a3a3a"


[label]
font_family = "Inter"
font_size = 10
font_weight = 400
font_color = "#d4d4d4"


[title]
font_family = "Inter"
font_size = 16
font_weight = 600
font_color = "#5e7ce0"


[subtitle]
font_size = 14
font_weight = 600
font_color = "#d4d4d8"


[description]
font_size = 10
font_weight = 600
font_color = "#d4d4d8"


[comment]
font_size = 8
font_color = "#cfcfcf"


[switch]
track_off = "#4a4a4a"
track_on = "#3d4a99"
handle_off = "#d4d4d4"
handle_on = "#d4d4d4"
track_disabled = "#4a4a4a"
handle_disabled = "#d4d4d4"


[checkbox]
box_size = 16
border = "#4a4a4a"
pressed = "#666667"
checked = "#5e7ce0"
disabled = "#4a4a4a"
font_color_disabled = "#666667"


[radio_button]
circle_size = 14
border = "#4a4a4a"
pressed = "#5e5e5e"
checked = "#5e7ce0"
disabled = "#4a4a4a"
font_color_disabled = "#666667"


[line_edit]
bgd = "#2a2a2a"
hover = ""
disabled = "#2a2a2a"

border = "#4a4a4a"
border_hover = "#5e7ce0"
border_edition = "#5e7ce0"
border_read_only = "#5e5e5e"

selection = "#5e7ce0"

button = "#666667"
button_hover = "#5e7ce0"
button_disabled = "#666667"

font_family = "Inter"
font_size = 10
font_weight = 400
font_color = "#d4d4d4"
font_color_read_only = "#666667"
font_color_disabled = "#666667"


[plain_text_edit]
# Use line_edit style


[scrollbar]
thickness = 8
normal = "#4a4a4a"
hover = "#4a4a4a"
pressed = "#5e5e5e"


[combobox]
# Use line_edit style


[spinbox]
button_hover = "#3a3a3a"
button_pressed = "#5e5e5e"
button_disabled = "#2a2a2a"


[strong_button]
bgd = "#5070d4"
hover = "#4c60b9"
pressed = "#5e7ce0"
disabled = "#2a2a2a"

font_family = "Inter"
font_size = 11
font_weight = 500
font_color = "#FFFFFF"
font_color_disabled = "#666667"


[strong_grey_button]
bgd = "#424242"
hover = "#3a3a3a"
pressed = "#424242"


[outlined_button]
bgd = "transparent"
hover = "#2a2a2a"
pressed = "#6a6a6a"
disabled = "#2a2a2a"

border = "#424242"
border_disabled = "#3a3a3a"

font_family = "Inter"
font_size = 11
font_weight = 400
font_color = "#d4d4d4"
font_color_disabled = "#666667"


[toggle_button]
bgd = "#2a2a2a"
hover = "#3a3a3a"
pressed = "#354185"
checked = "#3d4a99"
font_size = 9
font_weight = 400
font_color = "#d4d4d4"
font_color_disabled = "#666667"

[toggle_grey_button]
pressed = "#5e5e5e"
checked = "#6a6a6a"
disabled = "#2a2a2a"
font_color_disabled = "#666667"


[button_group]
bgd = "#2a2a2a"
hover = "#3a3a3a"
pressed = "#354185"
checked = "#3d4a99"
disabled = "#1c1d20"
disabled_checked = "#2a2a2a"

border = "#4a4a4a"

font_color = "#d4d4d4"
font_color_disabled = "#666667"


[grey_button_group]
checked = "#6a6a6a"
pressed = "#5e5e5e"




[frameless_button]
active = "#b0b0b0"
hover = "#d4d4d4"
pressed = "#5e7ce0"
checked = "#5e7ce0"
disabled = "#3a3a3a"
font_size = 9
font_weight = 400


[progress_bar]
thickness = 8
track = "#3a3a3a"
bar = "#5e7ce0"


[indet_progress_bar]
thickness = 8
track = "#2a2a2a"
bar = "#5e7ce0"


###################################################
# to be modified



[slider]
track = "#4a4a4a"
handle = "#5e7ce0"
handle_hover = "#5e7ce0"
handle_pressed = "#8a9eff"
track_height = 4
handle_width = 12
handle_height = 12



[log]
bgd = "#000000"
border = "#4a4a4a"
font_family = "monospace"
font_size = 12
font_color = "#b0b0b0"
text_bgd = "#111111"
